### ISSUE TITLE
http://localhost:3000/designer gives blank page

### ISSUE THREAD

**Issue by sumeetakumar** [EdgeVerve/oe-studio#1]
![2018-01-16 08_57_51-oe studio - slimjet](https://user-images.githubusercontent.com/1393444/34970663-ac1cee0a-fa9b-11e7-8c8a-eb2a1b84b897.png)

**Comment by kvsrohit** [comment]
@sumeetakumar 
Following the steps mentioned [in README](https://github.com/EdgeVerve/oe-studio#installing-oe-studio), the studio should show on /designer path.

Could you provide the browser you are using and the version?
Do you see any error in browser debug console?

**Comment by sumeetakumar** [comment]
Hi Rohit,

Thank you for fu.

The issue was actually relating to https://github.com/EdgeVerve/oe-ui-app Issue #1 posted by me where I was unable to run the command **oe ui-app** gave **error**: You don't seem to have a generator with the name “ui-app” installed.

Another issue is that on Windows **npm install** was not installing all sub project dependencies - **yarn** worked fine

I got studio working by following these steps: 

1) install mongodb and ensure serice is running
2) clone https://github.com/EdgeVerve/oe-ui-app
3) copy directory /app/templates/ into new directory outside the cloned repo called oeCloudAndStudio
4) add this line to bower.json "oe-studio": "https://github.com/EdgeVerve/oe-studio.git",
5) yarn
6) bower install. if asked for version choose the later version
7) open terminal, cd to  oeCloudAndStudio and run "node ."
8) browse to http://localhost:3000/designer
9) the designer GUI loads OK

**Comment by kvsrohit** [comment]
Closing as per user comments.
